### ISSUE TITLE
zizhan build is failing - how have you build it without OSS kernel

### ISSUE THREAD

**Issue by LeOS-GSI** [cupid-development/android_kernel_xiaomi_sm8450#4]
I have checked all zizhan available documentation. There is none for OSS kernel building. 
I have used all releated sources from your GIT. but rom building is failing all the time.

you have created a rom for zizahn. So there must a way to stop this error

attached the log. Hope here will be a better support as on telegram.

[verbose.log](https://github.com/cupid-development/android_kernel_xiaomi_sm8450/files/15375943/verbose.log)

**Comment by Gelbpunkt** [comment]
Read the XDA posts. They contain all the information you need.

**Comment by LeOS-GSI** [comment]
> Read the XDA posts. They contain all the information you need.

Pls read by your own. The xda post doesn't contain any building information for zizhan !!!!
The only information is, that zizhan is not supported  jet.

But you have created a rom, so there must be a way.

I really can't understand why you pointing on this not useable XDA post.

Seems you don't want that others can build the rom. That's sad and against open source philosophy.

**Comment by Gelbpunkt** [comment]
> The only information is, that zizhan is not supported jet.

Apparently you are incapable of reading past that line. Yes, zizhan is not supported in the main branches yet. Surprise!

> But you have created a rom, so there must be a way.

The way is described in the XDA posts.

> I really can't understand why you pointing on this not useable XDA post.

Because it is usable and you are just incapable of reading it. All sources and instructions are provided.

> That's sad and against open source philosophy.

No, you are just incompetent.

Please refrain from making further posts about this and consider re-reading the XDA threads a few times until you grasped all the contents.
